# Generated by Django 6.0.6 on 2026-06-16 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='NDC must match format #####-####-## (e.g. 00002-1433-02).', regex='^\\d{5}-\\d{4}-\\d{2}$')])),
                ('drug_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=100)),
                ('package_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('dea_schedule', models.CharField(blank=True, choices=[('II', 'Schedule II'), ('III', 'Schedule III'), ('IV', 'Schedule IV'), ('V', 'Schedule V')], max_length=3, null=True)),
            ],
            options={
                'ordering': ['drug_name'],
            },
        ),
    ]
